// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHotkeysConfig():Promise<Array<main.HotkeyConfig>>;

export function ReloadHotkeysAndListener():Promise<void>;
