// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHotkeysConfig() {
  return window['go']['main']['App']['GetHotkeysConfig']();
}

export function ReloadHotkeysAndListener() {
  return window['go']['main']['App']['ReloadHotkeysAndListener']();
}
