name: Build Windows Installer

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install NSIS (Scoop)
        shell: powershell
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails App
        run: |
          cd ui/windows
          wails build -nsis

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wails-binairies
          path: build/bin/*
